pipeline {

    agent {
        docker{
            image "python:2.7.16-slim"
        }
    }

    stages {
        stage('build') {
            when {
             changeset "**/vote/**"
            }
                 
            steps {
                echo 'Installing python pip for vote app'
                dir('vote'){
                        sh "pip install -i requirements.txt"
                }
            }
        }
        stage('test') {
            when {
             changeset "**/vote/**"
            }
                 
            steps {
                echo 'Installing and testing python pip for vote app'
                dir ('vote'){
                    sh "nosetests -v"
                }
            }
        }
        }
               
    post {
        always {
            echo "Pipeline for vote python pip run is complete.."
        }
        failure {
                slackSend (channel: "test-jenkins", message: "Build failure - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
                slackSend (channel: "test-jenkins", message: "Build succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
