version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: jlargaespada/vote:master
    ports:
    - 5001:80
    depends_on:
      - redis
    networks:
      - instavote

  result:
    image: jlargaespada/result:master
    ports:
     - 4000:4000
    depends_on:
      - db
    networks:
      - instavote


  worker:
    image: jlargaespada/worker:master
    depends_on:
      - redis
      - db
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
     - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust