pipeline {
    agent any

    tools {
        maven "Maven-3.6.1"
    }

    stages {
        stage('build') {
            steps {
                echo 'compiling worker app'
                dir('worker'){
			sh "mvn compile"
            }
            }
        stage('test') {
            steps {
                echo 'running tests on worker app'
                
                }
            }
        stage('package') {
            steps {
                echo 'packaging app'
                sleep 9
                }
            }
        }
    post {
        always {
            echo "Build pipeline for worker run is complete.."
        }
    }
}
}
