pipeline {
    agent any

    tools {
        maven "Maven-3.6.1"
    }

    stages {
        stage('build') {
            steps {
                echo 'compiling worker app'
                dir('worker'){
			sh "mvn compile"
            }
            }
		}
        stage('test') {
            steps {
                echo 'running tests on worker app'
		dir ('worker'){
		    sh "mvn clean test"	}                
                }
            }
        stage('package') {
            steps {
                echo 'packaging app'
                dir ("worker"){
			sh "mvn package"}
                }
            }
	}
	       
    post {
        always {
            echo "Pipeline for worker run is complete.."
            archiveArtifacts artifacts: '/**/target/*.jar', fingerprint: true

        }
    }
}
